name: Get User Email

on:
  workflow_dispatch:
    inputs:
      method:
        description: 'UsersHelper method name'
        required: true
        type: string

jobs:
  get-user:
    runs-on: arc-runner-dev-large
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Execute UsersHelper method
        env:
          TARGET_ENV: qa
          ENVIRONMENT: qa
          METHOD_NAME: ${{ github.event.inputs.method }}
        run: |
          # Create temporary TypeScript file in project root
          cat > ./execute-method.ts << 'EOF'
          import { UsersHelper } from './helpers/UsersHelper';
          
          (async () => {
            try {
              const methodName = process.env.METHOD_NAME;
              if (!methodName) {
                throw new Error('METHOD_NAME environment variable is required');
              }
              
              console.log('=== DEBUG: Environment Check ===');
              console.log('ENVIRONMENT:', process.env.ENVIRONMENT);
              console.log('TARGET_ENV:', process.env.TARGET_ENV);
              
              console.log('=== DEBUG: Method Selection ===');
              console.log('Method name received:', methodName);
              
              console.log('=== DEBUG: Creating UsersHelper instance ===');
              const usersHelper = new UsersHelper();
              
              console.log('=== DEBUG: Inspecting UsersHelper ===');
              console.log('Instance type:', typeof usersHelper);
              console.log('Constructor name:', usersHelper.constructor?.name);
              
              // Get ALL methods from prototype chain
              let current = usersHelper;
              const allMethods: string[] = [];
              while (current && current !== Object.prototype) {
                const methods = Object.getOwnPropertyNames(current)
                  .filter(name => name !== 'constructor' && typeof current[name] === 'function');
                allMethods.push(...methods);
                current = Object.getPrototypeOf(current);
              }
              
              const uniqueMethods = [...new Set(allMethods)];
              console.log('All available methods:', uniqueMethods.join(', '));
              
              // Check if method exists
              const methodExists = typeof usersHelper[methodName] === 'function';
              console.log(`Method "${methodName}" exists:`, methodExists);
              
              if (!methodExists) {
                throw new Error(`Method "${methodName}" not found. Available methods: ${uniqueMethods.join(', ')}`);
              }
              
              console.log('=== EXECUTING METHOD ===');
              console.log(`Calling: usersHelper.${methodName}()`);
              const email = await usersHelper[methodName]();
              console.log('USER_EMAIL_RESULT:', email);
            } catch (error: any) {
              console.error('ERROR:', error.message);
              console.error('Stack:', error.stack);
              process.exit(1);
            }
          })();
          EOF
          
          # Execute using npx tsx with TARGET_ENV and ENVIRONMENT
          # TARGET_ENV will be used by the code to load env vars from properties/qa/.env.qa
          # ENVIRONMENT is required by UsersHelper methods to check if they should run
          TARGET_ENV=qa ENVIRONMENT=qa npx tsx ./execute-method.ts
          
          # Cleanup
          rm -f ./execute-method.ts
        id: get-user-email

